const ADD_LANE = 'ADD_LANE';
const UPDATE_LANE = 'UPDATE_LANE';
const DELETE_LANE = 'DELETE_LANE';
const ACTIVATE_LANE_EDIT = 'ACTIVATE_LANE_EDIT';
const MOVE_NOTE = 'MOVE_NOTE'
export {
  ADD_LANE,
  UPDATE_LANE,
  DELETE_LANE,
  ACTIVATE_LANE_EDIT,
  MOVE_NOTE
};
