const ADD_NOTE = 'ADD_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const ACTIVATE_EDITING = 'ACTIVATE_EDITING';
const MOVE_NOTE = 'MOVE_NOTE'

export {
  ADD_NOTE,
  UPDATE_NOTE,
  DELETE_NOTE,
  ACTIVATE_EDITING,
  MOVE_NOTE
};
