const ADD_NOTE = 'ADD_NOTE';
const UPDATE_NOTE = 'UPDATE_NOTE';
const DELETE_NOTE = 'DELETE_NOTE';
const IS_EDITING_NOTE = 'IS_EDITING_NOTE';

export {
  ADD_NOTE,
  UPDATE_NOTE,
  DELETE_NOTE,
  IS_EDITING_NOTE
};
